# Generated by Django 2.1.2 on 2018-10-14 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohgeez', '0005_auto_20181013_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='latitude',
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='longitude',
            field=models.FloatField(default=0.0, editable=False),
        ),
    ]
